# Data Visualization Tools
This section is a quick overview of potential resources that can be utilized for data visualization: communciating data, results, and concepts through visual representations such as figures and diagrams. 

Here are some examples.

## Adobe Illustrator
Used for editing and combining figures as a vector graphics editor. 

### Common Uses in Biostatistics
- Editing plots exported from R (e.g., ggplot2 figures) 
- Can assist with combining multiple plots aesthetically
- Adjusts labels, fonts, and colors
- Can create schematic diagrams

Illustrator's effectiveness lies in its use in vector graphics, which means that the figures can be resized without loss in quality. 
Adobe Illustrator is not to be confused with Adobe Photoshop, a commonly used tool that is used to manipulate images, whereas Illustrator focuses on figure design and layout. 

## BioRender 
Used for creating scientific diagrams. Often used to explain basic wet lab techniques. 

### Common Uses in Biostatistics
- Biological pathway diagrams and simulation structures
- Graphical abstracts 
- Conceptual figures for study design clarity 

## Adobe InDesign 
Used for desgining posters and layouts. Organizes text and graphics. 

### Common Uses in Biostatistics
- Designing conference posters 
- Reports and manuscripts with figures that you can integrate
- Arrange multiple visualizations into one layout 
- Presentation materials

InDesign is especially useful with combining multiple figures. 

## Example workflow in PennSIVE
1. Analyze data and generate plots through ggplot2 in R 
2. Export figures as PDF 
3. Refine and combine figures in Adobe Illustrator
4. Create diagrams to help visualize simulation structure and results
5. Assemble into a final presentation in Adobe InDesign 

## Links to Data Visualization Resources

- [Adobe Illustrator](https://www.adobe.com/products/illustrator.html)
- [BioRender](https://www.biorender.com/)
- [Adobe InDesign](https://www.adobe.com/products/indesign.html)